### ISSUE TITLE
display source code

### ISSUE THREAD

**Issue by saejin-moon** [Infinite-Coder-001/khanapi-2#1]
GitHub is meant to be a collection of repositories for open-source projects; not necessarily a medium to access scripts on KA from jsDelivr. it would be preferred by the open-source community if you included the source code for the script updating the `data` folder repo in a `src` folder.

**Comment by Infinite-Coder-001** [comment]
Yes, I'll put there the source code as soon as I finish working on this. It's still under development, the code isn't finished yet.

**Comment by Infinite-Coder-001** [comment]
I added the source code now.
